### ISSUE TITLE
maybe add a flush dropbox option?

### ISSUE THREAD

**Issue by tanyav1995** [bsnacks000/datascience-project#3]
Yes, raw data is supposed to be immutable, but in cases that we do want to make a change on dropbox, should we have the option to flush the data store?
So far I've just been renaming the new file something different so that both versions are stored.

**Comment by bsnacks000** [comment]
Ok shouldn't be too difficult...

**Comment by bsnacks000** [comment]
@tvasyleva Added ``flush-dropbox`` here... baea5a9472f650720bf040b5fce9f2a7101d9802

This will clear raw and models folders on dropbox only... you can re-push like we talked about.  

If you want to integrate into the existing project add the code directly from this commit in the appropriate places (obviously replacing the cookiecutter tag with the project name) and run ``make install`` to rebuild the cli. Then you should be able to ``make flush-dropbox``... let me know if its not working for whatever reason.  I wrote and tested against my test repo and got it working but didn't try it with a fresh clone.
